// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjevyfyvrgvjgspxfikd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqZXZ5Znl2cmd2amdzcHhmaWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNTg3MzAsImV4cCI6MjA2ODYzNDczMH0.Akas8RncQ4g2a27DQ-jKnWcE8PdOJpIfCsvub6Ichkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});